language: haskell
ghc: 8.10.4
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database dbapi_test;' -U postgres
before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install --force-yes happy-1.19.3 alex-3.1.3
  - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.3/bin:$PATH
script:
  - cabal new-build && cabal new-test all --test-options="--color"