name:                pgrest
version:             0.1.0.0
github:              "pgrest"
license:             BSD3
author:              "Author name here"
maintainer:          "hoang.phan@gmail.com"
copyright:           "2020 Hoang Phan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pgrest#readme>

dependencies:
- base >= 4.7 && < 5
- HDBC
- HDBC-postgresql
- warp
- wai
- http-types
- bytestring
- aeson >= 1.3 && < 1.4.7
- network
- text
- optparse-applicative
- unordered-containers
- hspec
- network-uri
- heroku
- zlib

executables:
  pgrest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall